version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - ui

  mongo:
    image: mongo:4.4.1
    container_name: mongo
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - users
      - systems_service
    networks:
      - app-network

  users:
    build: ./users-microservice
    container_name: users_service
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  systems_service:
    build: ./systems-microservice
    container_name: systems_service
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  ui:
    build: ./ui
    container_name: ui
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_FILE=/etc/mongo-express/config.js
      - ME_CONFIG_BASICAUTH=false
    volumes:
      - ./path/to/config.js:/etc/mongo-express/config.js
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:

volumes:
  mongo-data:
